version: '3'
#define 2 services: web and rabbit
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
  mediview:
    build: .
    ports:
      - "20001:20001"
    volumes:
      - .:/code
    labels:
      NAME: "mediview"